# Generated by Django 5.1.4 on 2024-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product1', models.IntegerField()),
                ('product2', models.IntegerField()),
                ('product3', models.IntegerField()),
                ('product4', models.IntegerField()),
                ('product5', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Kitchenware',
        ),
    ]
